#!/bin/bash

#提示用户输入
echo -n "Pleasw enter number : "
read n #读入输入的值放到变量n中
sd=0
rev=""
on=$n #将变量n的值保存到变量on中，方便以后用到
echo "You put number is $n"
while [ $n -gt 0 ]
do
    sd=$(( $n % 10 )) #求余
    n=$(( $n / 10 ))  #去掉当前的最后一位数后剩下的数
    rev="$rev$sd" #将当前的最后一位数放到字符串之后
done
echo  "$on in a reverse order $rev"
