#!/bin/bash

#将第一个命令行参数传递给变量a,第二个命令行参数传递给变量b
a=$1
b=$2

#判断a或者b变量是否为空，只要有一个为空就打印提示语句并退出
if [ -z $a ] || [ -z $b ]
then
    echo "please enter 2 no"
    exit 1

#判断a和b的大小，并根据判断结果打印语句
fi
if [ $a -eq $b ] ; then
    echo "number a = number b"
else if [ $a -gt $b ]
    then
        echo "number a>number b"
    elif [ $a -lt $b ]
        then
            echo "number a<number b"
    fi
fi
